/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as NotFoundPageRouteImport } from './routes/not-found-page'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisitIndexRouteImport } from './routes/visit/index'
import { Route as VisionIndexRouteImport } from './routes/vision/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as CareersIndexRouteImport } from './routes/careers/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as VisitVirtualTourRouteImport } from './routes/visit/virtual-tour'
import { Route as VisionValuesRouteImport } from './routes/vision/values'
import { Route as VisionStrategyRouteImport } from './routes/vision/strategy'
import { Route as VisionReportsRouteImport } from './routes/vision/reports'
import { Route as VisionMissionRouteImport } from './routes/vision/mission'
import { Route as UpdatesNewsRouteImport } from './routes/updates/news'
import { Route as UpdatesEventsRouteImport } from './routes/updates/events'
import { Route as StudentLifeStudentSupportRouteImport } from './routes/student-life/student-support'
import { Route as StudentLifeStudentExperienceRouteImport } from './routes/student-life/student-experience'
import { Route as StudentLifeCampusLifeRouteImport } from './routes/student-life/campus-life'
import { Route as ResearchIotLabsRouteImport } from './routes/research/iot-labs'
import { Route as ResearchInnovationCentersRouteImport } from './routes/research/innovation-centers'
import { Route as ResearchAiLabsRouteImport } from './routes/research/ai-labs'
import { Route as ProgramsBtechEdItRouteImport } from './routes/programs/btech-ed-it'
import { Route as ProgramsBitRouteImport } from './routes/programs/bit'
import { Route as CommunityInternationalRouteImport } from './routes/community/international'
import { Route as CommunityFacultyRouteImport } from './routes/community/faculty'
import { Route as CommunityBoardMembersRouteImport } from './routes/community/board-members'
import { Route as CommunityAdvisorsRouteImport } from './routes/community/advisors'
import { Route as CommunityAdministrationRouteImport } from './routes/community/administration'
import { Route as CareersPlacementsRouteImport } from './routes/careers/placements'
import { Route as CareersGraduateSuccessRouteImport } from './routes/careers/graduate-success'
import { Route as CareersCareerPathsRouteImport } from './routes/careers/career-paths'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAuthedRouteImport } from './routes/admin/_authed'
import { Route as AcademicsScholarshipsRouteImport } from './routes/academics/scholarships'
import { Route as AcademicsResearchRouteImport } from './routes/academics/research'
import { Route as AcademicsAdmissionsRouteImport } from './routes/academics/admissions'
import { Route as AboutPublicationsRouteImport } from './routes/about/publications'
import { Route as AboutLegacyRouteImport } from './routes/about/legacy'
import { Route as AboutKuAffiliationRouteImport } from './routes/about/ku-affiliation'
import { Route as AboutIndustryExposureRouteImport } from './routes/about/industry-exposure'
import { Route as AboutGovernanceRouteImport } from './routes/about/governance'
import { Route as AdminAuthedIndexRouteImport } from './routes/admin/_authed/index'
import { Route as AdminAuthedSiteRouteImport } from './routes/admin/_authed/site'
import { Route as AdminAuthedScholarshipsRouteImport } from './routes/admin/_authed/scholarships'
import { Route as AdminAuthedProgramsRouteImport } from './routes/admin/_authed/programs'
import { Route as AdminAuthedOpeningsRouteImport } from './routes/admin/_authed/openings'
import { Route as AdminAuthedNewsRouteImport } from './routes/admin/_authed/news'
import { Route as AdminAuthedChatbotRouteImport } from './routes/admin/_authed/chatbot'

const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundPageRoute = NotFoundPageRouteImport.update({
  id: '/not-found-page',
  path: '/not-found-page',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitIndexRoute = VisitIndexRouteImport.update({
  id: '/visit/',
  path: '/visit/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionIndexRoute = VisionIndexRouteImport.update({
  id: '/vision/',
  path: '/vision/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsRoute,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitVirtualTourRoute = VisitVirtualTourRouteImport.update({
  id: '/visit/virtual-tour',
  path: '/visit/virtual-tour',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionValuesRoute = VisionValuesRouteImport.update({
  id: '/vision/values',
  path: '/vision/values',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionStrategyRoute = VisionStrategyRouteImport.update({
  id: '/vision/strategy',
  path: '/vision/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionReportsRoute = VisionReportsRouteImport.update({
  id: '/vision/reports',
  path: '/vision/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionMissionRoute = VisionMissionRouteImport.update({
  id: '/vision/mission',
  path: '/vision/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesNewsRoute = UpdatesNewsRouteImport.update({
  id: '/updates/news',
  path: '/updates/news',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesEventsRoute = UpdatesEventsRouteImport.update({
  id: '/updates/events',
  path: '/updates/events',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLifeStudentSupportRoute =
  StudentLifeStudentSupportRouteImport.update({
    id: '/student-life/student-support',
    path: '/student-life/student-support',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentLifeStudentExperienceRoute =
  StudentLifeStudentExperienceRouteImport.update({
    id: '/student-life/student-experience',
    path: '/student-life/student-experience',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentLifeCampusLifeRoute = StudentLifeCampusLifeRouteImport.update({
  id: '/student-life/campus-life',
  path: '/student-life/campus-life',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIotLabsRoute = ResearchIotLabsRouteImport.update({
  id: '/research/iot-labs',
  path: '/research/iot-labs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchInnovationCentersRoute =
  ResearchInnovationCentersRouteImport.update({
    id: '/research/innovation-centers',
    path: '/research/innovation-centers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResearchAiLabsRoute = ResearchAiLabsRouteImport.update({
  id: '/research/ai-labs',
  path: '/research/ai-labs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsBtechEdItRoute = ProgramsBtechEdItRouteImport.update({
  id: '/btech-ed-it',
  path: '/btech-ed-it',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsBitRoute = ProgramsBitRouteImport.update({
  id: '/bit',
  path: '/bit',
  getParentRoute: () => ProgramsRoute,
} as any)
const CommunityInternationalRoute = CommunityInternationalRouteImport.update({
  id: '/community/international',
  path: '/community/international',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityFacultyRoute = CommunityFacultyRouteImport.update({
  id: '/community/faculty',
  path: '/community/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityBoardMembersRoute = CommunityBoardMembersRouteImport.update({
  id: '/community/board-members',
  path: '/community/board-members',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityAdvisorsRoute = CommunityAdvisorsRouteImport.update({
  id: '/community/advisors',
  path: '/community/advisors',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityAdministrationRoute = CommunityAdministrationRouteImport.update({
  id: '/community/administration',
  path: '/community/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersPlacementsRoute = CareersPlacementsRouteImport.update({
  id: '/careers/placements',
  path: '/careers/placements',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersGraduateSuccessRoute = CareersGraduateSuccessRouteImport.update({
  id: '/careers/graduate-success',
  path: '/careers/graduate-success',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersCareerPathsRoute = CareersCareerPathsRouteImport.update({
  id: '/careers/career-paths',
  path: '/careers/career-paths',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedRoute = AdminAuthedRouteImport.update({
  id: '/admin/_authed',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsScholarshipsRoute = AcademicsScholarshipsRouteImport.update({
  id: '/academics/scholarships',
  path: '/academics/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsResearchRoute = AcademicsResearchRouteImport.update({
  id: '/academics/research',
  path: '/academics/research',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsAdmissionsRoute = AcademicsAdmissionsRouteImport.update({
  id: '/academics/admissions',
  path: '/academics/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPublicationsRoute = AboutPublicationsRouteImport.update({
  id: '/about/publications',
  path: '/about/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutLegacyRoute = AboutLegacyRouteImport.update({
  id: '/about/legacy',
  path: '/about/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutKuAffiliationRoute = AboutKuAffiliationRouteImport.update({
  id: '/about/ku-affiliation',
  path: '/about/ku-affiliation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndustryExposureRoute = AboutIndustryExposureRouteImport.update({
  id: '/about/industry-exposure',
  path: '/about/industry-exposure',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutGovernanceRoute = AboutGovernanceRouteImport.update({
  id: '/about/governance',
  path: '/about/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedIndexRoute = AdminAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedSiteRoute = AdminAuthedSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedScholarshipsRoute = AdminAuthedScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedProgramsRoute = AdminAuthedProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedOpeningsRoute = AdminAuthedOpeningsRouteImport.update({
  id: '/openings',
  path: '/openings',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedNewsRoute = AdminAuthedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedChatbotRoute = AdminAuthedChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AdminAuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/maintenance': typeof MaintenanceRoute
  '/not-found-page': typeof NotFoundPageRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/about/governance': typeof AboutGovernanceRoute
  '/about/industry-exposure': typeof AboutIndustryExposureRoute
  '/about/ku-affiliation': typeof AboutKuAffiliationRoute
  '/about/legacy': typeof AboutLegacyRoute
  '/about/publications': typeof AboutPublicationsRoute
  '/academics/admissions': typeof AcademicsAdmissionsRoute
  '/academics/research': typeof AcademicsResearchRoute
  '/academics/scholarships': typeof AcademicsScholarshipsRoute
  '/admin': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/careers/career-paths': typeof CareersCareerPathsRoute
  '/careers/graduate-success': typeof CareersGraduateSuccessRoute
  '/careers/placements': typeof CareersPlacementsRoute
  '/community/administration': typeof CommunityAdministrationRoute
  '/community/advisors': typeof CommunityAdvisorsRoute
  '/community/board-members': typeof CommunityBoardMembersRoute
  '/community/faculty': typeof CommunityFacultyRoute
  '/community/international': typeof CommunityInternationalRoute
  '/programs/bit': typeof ProgramsBitRoute
  '/programs/btech-ed-it': typeof ProgramsBtechEdItRoute
  '/research/ai-labs': typeof ResearchAiLabsRoute
  '/research/innovation-centers': typeof ResearchInnovationCentersRoute
  '/research/iot-labs': typeof ResearchIotLabsRoute
  '/student-life/campus-life': typeof StudentLifeCampusLifeRoute
  '/student-life/student-experience': typeof StudentLifeStudentExperienceRoute
  '/student-life/student-support': typeof StudentLifeStudentSupportRoute
  '/updates/events': typeof UpdatesEventsRoute
  '/updates/news': typeof UpdatesNewsRoute
  '/vision/mission': typeof VisionMissionRoute
  '/vision/reports': typeof VisionReportsRoute
  '/vision/strategy': typeof VisionStrategyRoute
  '/vision/values': typeof VisionValuesRoute
  '/visit/virtual-tour': typeof VisitVirtualTourRoute
  '/about/': typeof AboutIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/vision/': typeof VisionIndexRoute
  '/visit/': typeof VisitIndexRoute
  '/admin/chatbot': typeof AdminAuthedChatbotRoute
  '/admin/news': typeof AdminAuthedNewsRoute
  '/admin/openings': typeof AdminAuthedOpeningsRoute
  '/admin/programs': typeof AdminAuthedProgramsRoute
  '/admin/scholarships': typeof AdminAuthedScholarshipsRoute
  '/admin/site': typeof AdminAuthedSiteRoute
  '/admin/': typeof AdminAuthedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/maintenance': typeof MaintenanceRoute
  '/not-found-page': typeof NotFoundPageRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/about/industry-exposure': typeof AboutIndustryExposureRoute
  '/about/ku-affiliation': typeof AboutKuAffiliationRoute
  '/about/legacy': typeof AboutLegacyRoute
  '/about/publications': typeof AboutPublicationsRoute
  '/academics/admissions': typeof AcademicsAdmissionsRoute
  '/academics/research': typeof AcademicsResearchRoute
  '/academics/scholarships': typeof AcademicsScholarshipsRoute
  '/admin/login': typeof AdminLoginRoute
  '/careers/career-paths': typeof CareersCareerPathsRoute
  '/careers/graduate-success': typeof CareersGraduateSuccessRoute
  '/careers/placements': typeof CareersPlacementsRoute
  '/community/administration': typeof CommunityAdministrationRoute
  '/community/advisors': typeof CommunityAdvisorsRoute
  '/community/board-members': typeof CommunityBoardMembersRoute
  '/community/faculty': typeof CommunityFacultyRoute
  '/community/international': typeof CommunityInternationalRoute
  '/programs/bit': typeof ProgramsBitRoute
  '/programs/btech-ed-it': typeof ProgramsBtechEdItRoute
  '/research/ai-labs': typeof ResearchAiLabsRoute
  '/research/innovation-centers': typeof ResearchInnovationCentersRoute
  '/research/iot-labs': typeof ResearchIotLabsRoute
  '/student-life/campus-life': typeof StudentLifeCampusLifeRoute
  '/student-life/student-experience': typeof StudentLifeStudentExperienceRoute
  '/student-life/student-support': typeof StudentLifeStudentSupportRoute
  '/updates/events': typeof UpdatesEventsRoute
  '/updates/news': typeof UpdatesNewsRoute
  '/vision/mission': typeof VisionMissionRoute
  '/vision/reports': typeof VisionReportsRoute
  '/vision/strategy': typeof VisionStrategyRoute
  '/vision/values': typeof VisionValuesRoute
  '/visit/virtual-tour': typeof VisitVirtualTourRoute
  '/about': typeof AboutIndexRoute
  '/careers': typeof CareersIndexRoute
  '/community': typeof CommunityIndexRoute
  '/contact': typeof ContactIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/vision': typeof VisionIndexRoute
  '/visit': typeof VisitIndexRoute
  '/admin/chatbot': typeof AdminAuthedChatbotRoute
  '/admin/news': typeof AdminAuthedNewsRoute
  '/admin/openings': typeof AdminAuthedOpeningsRoute
  '/admin/programs': typeof AdminAuthedProgramsRoute
  '/admin/scholarships': typeof AdminAuthedScholarshipsRoute
  '/admin/site': typeof AdminAuthedSiteRoute
  '/admin': typeof AdminAuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/maintenance': typeof MaintenanceRoute
  '/not-found-page': typeof NotFoundPageRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/about/governance': typeof AboutGovernanceRoute
  '/about/industry-exposure': typeof AboutIndustryExposureRoute
  '/about/ku-affiliation': typeof AboutKuAffiliationRoute
  '/about/legacy': typeof AboutLegacyRoute
  '/about/publications': typeof AboutPublicationsRoute
  '/academics/admissions': typeof AcademicsAdmissionsRoute
  '/academics/research': typeof AcademicsResearchRoute
  '/academics/scholarships': typeof AcademicsScholarshipsRoute
  '/admin/_authed': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/careers/career-paths': typeof CareersCareerPathsRoute
  '/careers/graduate-success': typeof CareersGraduateSuccessRoute
  '/careers/placements': typeof CareersPlacementsRoute
  '/community/administration': typeof CommunityAdministrationRoute
  '/community/advisors': typeof CommunityAdvisorsRoute
  '/community/board-members': typeof CommunityBoardMembersRoute
  '/community/faculty': typeof CommunityFacultyRoute
  '/community/international': typeof CommunityInternationalRoute
  '/programs/bit': typeof ProgramsBitRoute
  '/programs/btech-ed-it': typeof ProgramsBtechEdItRoute
  '/research/ai-labs': typeof ResearchAiLabsRoute
  '/research/innovation-centers': typeof ResearchInnovationCentersRoute
  '/research/iot-labs': typeof ResearchIotLabsRoute
  '/student-life/campus-life': typeof StudentLifeCampusLifeRoute
  '/student-life/student-experience': typeof StudentLifeStudentExperienceRoute
  '/student-life/student-support': typeof StudentLifeStudentSupportRoute
  '/updates/events': typeof UpdatesEventsRoute
  '/updates/news': typeof UpdatesNewsRoute
  '/vision/mission': typeof VisionMissionRoute
  '/vision/reports': typeof VisionReportsRoute
  '/vision/strategy': typeof VisionStrategyRoute
  '/vision/values': typeof VisionValuesRoute
  '/visit/virtual-tour': typeof VisitVirtualTourRoute
  '/about/': typeof AboutIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/vision/': typeof VisionIndexRoute
  '/visit/': typeof VisitIndexRoute
  '/admin/_authed/chatbot': typeof AdminAuthedChatbotRoute
  '/admin/_authed/news': typeof AdminAuthedNewsRoute
  '/admin/_authed/openings': typeof AdminAuthedOpeningsRoute
  '/admin/_authed/programs': typeof AdminAuthedProgramsRoute
  '/admin/_authed/scholarships': typeof AdminAuthedScholarshipsRoute
  '/admin/_authed/site': typeof AdminAuthedSiteRoute
  '/admin/_authed/': typeof AdminAuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/maintenance'
    | '/not-found-page'
    | '/programs'
    | '/about/governance'
    | '/about/industry-exposure'
    | '/about/ku-affiliation'
    | '/about/legacy'
    | '/about/publications'
    | '/academics/admissions'
    | '/academics/research'
    | '/academics/scholarships'
    | '/admin'
    | '/admin/login'
    | '/careers/career-paths'
    | '/careers/graduate-success'
    | '/careers/placements'
    | '/community/administration'
    | '/community/advisors'
    | '/community/board-members'
    | '/community/faculty'
    | '/community/international'
    | '/programs/bit'
    | '/programs/btech-ed-it'
    | '/research/ai-labs'
    | '/research/innovation-centers'
    | '/research/iot-labs'
    | '/student-life/campus-life'
    | '/student-life/student-experience'
    | '/student-life/student-support'
    | '/updates/events'
    | '/updates/news'
    | '/vision/mission'
    | '/vision/reports'
    | '/vision/strategy'
    | '/vision/values'
    | '/visit/virtual-tour'
    | '/about/'
    | '/careers/'
    | '/community/'
    | '/contact/'
    | '/programs/'
    | '/vision/'
    | '/visit/'
    | '/admin/chatbot'
    | '/admin/news'
    | '/admin/openings'
    | '/admin/programs'
    | '/admin/scholarships'
    | '/admin/site'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/maintenance'
    | '/not-found-page'
    | '/about/governance'
    | '/about/industry-exposure'
    | '/about/ku-affiliation'
    | '/about/legacy'
    | '/about/publications'
    | '/academics/admissions'
    | '/academics/research'
    | '/academics/scholarships'
    | '/admin/login'
    | '/careers/career-paths'
    | '/careers/graduate-success'
    | '/careers/placements'
    | '/community/administration'
    | '/community/advisors'
    | '/community/board-members'
    | '/community/faculty'
    | '/community/international'
    | '/programs/bit'
    | '/programs/btech-ed-it'
    | '/research/ai-labs'
    | '/research/innovation-centers'
    | '/research/iot-labs'
    | '/student-life/campus-life'
    | '/student-life/student-experience'
    | '/student-life/student-support'
    | '/updates/events'
    | '/updates/news'
    | '/vision/mission'
    | '/vision/reports'
    | '/vision/strategy'
    | '/vision/values'
    | '/visit/virtual-tour'
    | '/about'
    | '/careers'
    | '/community'
    | '/contact'
    | '/programs'
    | '/vision'
    | '/visit'
    | '/admin/chatbot'
    | '/admin/news'
    | '/admin/openings'
    | '/admin/programs'
    | '/admin/scholarships'
    | '/admin/site'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/maintenance'
    | '/not-found-page'
    | '/programs'
    | '/about/governance'
    | '/about/industry-exposure'
    | '/about/ku-affiliation'
    | '/about/legacy'
    | '/about/publications'
    | '/academics/admissions'
    | '/academics/research'
    | '/academics/scholarships'
    | '/admin/_authed'
    | '/admin/login'
    | '/careers/career-paths'
    | '/careers/graduate-success'
    | '/careers/placements'
    | '/community/administration'
    | '/community/advisors'
    | '/community/board-members'
    | '/community/faculty'
    | '/community/international'
    | '/programs/bit'
    | '/programs/btech-ed-it'
    | '/research/ai-labs'
    | '/research/innovation-centers'
    | '/research/iot-labs'
    | '/student-life/campus-life'
    | '/student-life/student-experience'
    | '/student-life/student-support'
    | '/updates/events'
    | '/updates/news'
    | '/vision/mission'
    | '/vision/reports'
    | '/vision/strategy'
    | '/vision/values'
    | '/visit/virtual-tour'
    | '/about/'
    | '/careers/'
    | '/community/'
    | '/contact/'
    | '/programs/'
    | '/vision/'
    | '/visit/'
    | '/admin/_authed/chatbot'
    | '/admin/_authed/news'
    | '/admin/_authed/openings'
    | '/admin/_authed/programs'
    | '/admin/_authed/scholarships'
    | '/admin/_authed/site'
    | '/admin/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  MaintenanceRoute: typeof MaintenanceRoute
  NotFoundPageRoute: typeof NotFoundPageRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  AboutGovernanceRoute: typeof AboutGovernanceRoute
  AboutIndustryExposureRoute: typeof AboutIndustryExposureRoute
  AboutKuAffiliationRoute: typeof AboutKuAffiliationRoute
  AboutLegacyRoute: typeof AboutLegacyRoute
  AboutPublicationsRoute: typeof AboutPublicationsRoute
  AcademicsAdmissionsRoute: typeof AcademicsAdmissionsRoute
  AcademicsResearchRoute: typeof AcademicsResearchRoute
  AcademicsScholarshipsRoute: typeof AcademicsScholarshipsRoute
  AdminAuthedRoute: typeof AdminAuthedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  CareersCareerPathsRoute: typeof CareersCareerPathsRoute
  CareersGraduateSuccessRoute: typeof CareersGraduateSuccessRoute
  CareersPlacementsRoute: typeof CareersPlacementsRoute
  CommunityAdministrationRoute: typeof CommunityAdministrationRoute
  CommunityAdvisorsRoute: typeof CommunityAdvisorsRoute
  CommunityBoardMembersRoute: typeof CommunityBoardMembersRoute
  CommunityFacultyRoute: typeof CommunityFacultyRoute
  CommunityInternationalRoute: typeof CommunityInternationalRoute
  ResearchAiLabsRoute: typeof ResearchAiLabsRoute
  ResearchInnovationCentersRoute: typeof ResearchInnovationCentersRoute
  ResearchIotLabsRoute: typeof ResearchIotLabsRoute
  StudentLifeCampusLifeRoute: typeof StudentLifeCampusLifeRoute
  StudentLifeStudentExperienceRoute: typeof StudentLifeStudentExperienceRoute
  StudentLifeStudentSupportRoute: typeof StudentLifeStudentSupportRoute
  UpdatesEventsRoute: typeof UpdatesEventsRoute
  UpdatesNewsRoute: typeof UpdatesNewsRoute
  VisionMissionRoute: typeof VisionMissionRoute
  VisionReportsRoute: typeof VisionReportsRoute
  VisionStrategyRoute: typeof VisionStrategyRoute
  VisionValuesRoute: typeof VisionValuesRoute
  VisitVirtualTourRoute: typeof VisitVirtualTourRoute
  AboutIndexRoute: typeof AboutIndexRoute
  CareersIndexRoute: typeof CareersIndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  VisionIndexRoute: typeof VisionIndexRoute
  VisitIndexRoute: typeof VisitIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found-page': {
      id: '/not-found-page'
      path: '/not-found-page'
      fullPath: '/not-found-page'
      preLoaderRoute: typeof NotFoundPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit/': {
      id: '/visit/'
      path: '/visit'
      fullPath: '/visit/'
      preLoaderRoute: typeof VisitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision/': {
      id: '/vision/'
      path: '/vision'
      fullPath: '/vision/'
      preLoaderRoute: typeof VisionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit/virtual-tour': {
      id: '/visit/virtual-tour'
      path: '/visit/virtual-tour'
      fullPath: '/visit/virtual-tour'
      preLoaderRoute: typeof VisitVirtualTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision/values': {
      id: '/vision/values'
      path: '/vision/values'
      fullPath: '/vision/values'
      preLoaderRoute: typeof VisionValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision/strategy': {
      id: '/vision/strategy'
      path: '/vision/strategy'
      fullPath: '/vision/strategy'
      preLoaderRoute: typeof VisionStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision/reports': {
      id: '/vision/reports'
      path: '/vision/reports'
      fullPath: '/vision/reports'
      preLoaderRoute: typeof VisionReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision/mission': {
      id: '/vision/mission'
      path: '/vision/mission'
      fullPath: '/vision/mission'
      preLoaderRoute: typeof VisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/news': {
      id: '/updates/news'
      path: '/updates/news'
      fullPath: '/updates/news'
      preLoaderRoute: typeof UpdatesNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/events': {
      id: '/updates/events'
      path: '/updates/events'
      fullPath: '/updates/events'
      preLoaderRoute: typeof UpdatesEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life/student-support': {
      id: '/student-life/student-support'
      path: '/student-life/student-support'
      fullPath: '/student-life/student-support'
      preLoaderRoute: typeof StudentLifeStudentSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life/student-experience': {
      id: '/student-life/student-experience'
      path: '/student-life/student-experience'
      fullPath: '/student-life/student-experience'
      preLoaderRoute: typeof StudentLifeStudentExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life/campus-life': {
      id: '/student-life/campus-life'
      path: '/student-life/campus-life'
      fullPath: '/student-life/campus-life'
      preLoaderRoute: typeof StudentLifeCampusLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/iot-labs': {
      id: '/research/iot-labs'
      path: '/research/iot-labs'
      fullPath: '/research/iot-labs'
      preLoaderRoute: typeof ResearchIotLabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/innovation-centers': {
      id: '/research/innovation-centers'
      path: '/research/innovation-centers'
      fullPath: '/research/innovation-centers'
      preLoaderRoute: typeof ResearchInnovationCentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/ai-labs': {
      id: '/research/ai-labs'
      path: '/research/ai-labs'
      fullPath: '/research/ai-labs'
      preLoaderRoute: typeof ResearchAiLabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/btech-ed-it': {
      id: '/programs/btech-ed-it'
      path: '/btech-ed-it'
      fullPath: '/programs/btech-ed-it'
      preLoaderRoute: typeof ProgramsBtechEdItRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/bit': {
      id: '/programs/bit'
      path: '/bit'
      fullPath: '/programs/bit'
      preLoaderRoute: typeof ProgramsBitRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/community/international': {
      id: '/community/international'
      path: '/community/international'
      fullPath: '/community/international'
      preLoaderRoute: typeof CommunityInternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/faculty': {
      id: '/community/faculty'
      path: '/community/faculty'
      fullPath: '/community/faculty'
      preLoaderRoute: typeof CommunityFacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/board-members': {
      id: '/community/board-members'
      path: '/community/board-members'
      fullPath: '/community/board-members'
      preLoaderRoute: typeof CommunityBoardMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/advisors': {
      id: '/community/advisors'
      path: '/community/advisors'
      fullPath: '/community/advisors'
      preLoaderRoute: typeof CommunityAdvisorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/administration': {
      id: '/community/administration'
      path: '/community/administration'
      fullPath: '/community/administration'
      preLoaderRoute: typeof CommunityAdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/placements': {
      id: '/careers/placements'
      path: '/careers/placements'
      fullPath: '/careers/placements'
      preLoaderRoute: typeof CareersPlacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/graduate-success': {
      id: '/careers/graduate-success'
      path: '/careers/graduate-success'
      fullPath: '/careers/graduate-success'
      preLoaderRoute: typeof CareersGraduateSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/career-paths': {
      id: '/careers/career-paths'
      path: '/careers/career-paths'
      fullPath: '/careers/career-paths'
      preLoaderRoute: typeof CareersCareerPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/scholarships': {
      id: '/academics/scholarships'
      path: '/academics/scholarships'
      fullPath: '/academics/scholarships'
      preLoaderRoute: typeof AcademicsScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/research': {
      id: '/academics/research'
      path: '/academics/research'
      fullPath: '/academics/research'
      preLoaderRoute: typeof AcademicsResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/admissions': {
      id: '/academics/admissions'
      path: '/academics/admissions'
      fullPath: '/academics/admissions'
      preLoaderRoute: typeof AcademicsAdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/publications': {
      id: '/about/publications'
      path: '/about/publications'
      fullPath: '/about/publications'
      preLoaderRoute: typeof AboutPublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/legacy': {
      id: '/about/legacy'
      path: '/about/legacy'
      fullPath: '/about/legacy'
      preLoaderRoute: typeof AboutLegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/ku-affiliation': {
      id: '/about/ku-affiliation'
      path: '/about/ku-affiliation'
      fullPath: '/about/ku-affiliation'
      preLoaderRoute: typeof AboutKuAffiliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/industry-exposure': {
      id: '/about/industry-exposure'
      path: '/about/industry-exposure'
      fullPath: '/about/industry-exposure'
      preLoaderRoute: typeof AboutIndustryExposureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/governance': {
      id: '/about/governance'
      path: '/about/governance'
      fullPath: '/about/governance'
      preLoaderRoute: typeof AboutGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed/': {
      id: '/admin/_authed/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthedIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/site': {
      id: '/admin/_authed/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AdminAuthedSiteRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/scholarships': {
      id: '/admin/_authed/scholarships'
      path: '/scholarships'
      fullPath: '/admin/scholarships'
      preLoaderRoute: typeof AdminAuthedScholarshipsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/programs': {
      id: '/admin/_authed/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminAuthedProgramsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/openings': {
      id: '/admin/_authed/openings'
      path: '/openings'
      fullPath: '/admin/openings'
      preLoaderRoute: typeof AdminAuthedOpeningsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/news': {
      id: '/admin/_authed/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminAuthedNewsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/chatbot': {
      id: '/admin/_authed/chatbot'
      path: '/chatbot'
      fullPath: '/admin/chatbot'
      preLoaderRoute: typeof AdminAuthedChatbotRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
  }
}

interface ProgramsRouteChildren {
  ProgramsBitRoute: typeof ProgramsBitRoute
  ProgramsBtechEdItRoute: typeof ProgramsBtechEdItRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsBitRoute: ProgramsBitRoute,
  ProgramsBtechEdItRoute: ProgramsBtechEdItRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

interface AdminAuthedRouteChildren {
  AdminAuthedChatbotRoute: typeof AdminAuthedChatbotRoute
  AdminAuthedNewsRoute: typeof AdminAuthedNewsRoute
  AdminAuthedOpeningsRoute: typeof AdminAuthedOpeningsRoute
  AdminAuthedProgramsRoute: typeof AdminAuthedProgramsRoute
  AdminAuthedScholarshipsRoute: typeof AdminAuthedScholarshipsRoute
  AdminAuthedSiteRoute: typeof AdminAuthedSiteRoute
  AdminAuthedIndexRoute: typeof AdminAuthedIndexRoute
}

const AdminAuthedRouteChildren: AdminAuthedRouteChildren = {
  AdminAuthedChatbotRoute: AdminAuthedChatbotRoute,
  AdminAuthedNewsRoute: AdminAuthedNewsRoute,
  AdminAuthedOpeningsRoute: AdminAuthedOpeningsRoute,
  AdminAuthedProgramsRoute: AdminAuthedProgramsRoute,
  AdminAuthedScholarshipsRoute: AdminAuthedScholarshipsRoute,
  AdminAuthedSiteRoute: AdminAuthedSiteRoute,
  AdminAuthedIndexRoute: AdminAuthedIndexRoute,
}

const AdminAuthedRouteWithChildren = AdminAuthedRoute._addFileChildren(
  AdminAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  MaintenanceRoute: MaintenanceRoute,
  NotFoundPageRoute: NotFoundPageRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  AboutGovernanceRoute: AboutGovernanceRoute,
  AboutIndustryExposureRoute: AboutIndustryExposureRoute,
  AboutKuAffiliationRoute: AboutKuAffiliationRoute,
  AboutLegacyRoute: AboutLegacyRoute,
  AboutPublicationsRoute: AboutPublicationsRoute,
  AcademicsAdmissionsRoute: AcademicsAdmissionsRoute,
  AcademicsResearchRoute: AcademicsResearchRoute,
  AcademicsScholarshipsRoute: AcademicsScholarshipsRoute,
  AdminAuthedRoute: AdminAuthedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  CareersCareerPathsRoute: CareersCareerPathsRoute,
  CareersGraduateSuccessRoute: CareersGraduateSuccessRoute,
  CareersPlacementsRoute: CareersPlacementsRoute,
  CommunityAdministrationRoute: CommunityAdministrationRoute,
  CommunityAdvisorsRoute: CommunityAdvisorsRoute,
  CommunityBoardMembersRoute: CommunityBoardMembersRoute,
  CommunityFacultyRoute: CommunityFacultyRoute,
  CommunityInternationalRoute: CommunityInternationalRoute,
  ResearchAiLabsRoute: ResearchAiLabsRoute,
  ResearchInnovationCentersRoute: ResearchInnovationCentersRoute,
  ResearchIotLabsRoute: ResearchIotLabsRoute,
  StudentLifeCampusLifeRoute: StudentLifeCampusLifeRoute,
  StudentLifeStudentExperienceRoute: StudentLifeStudentExperienceRoute,
  StudentLifeStudentSupportRoute: StudentLifeStudentSupportRoute,
  UpdatesEventsRoute: UpdatesEventsRoute,
  UpdatesNewsRoute: UpdatesNewsRoute,
  VisionMissionRoute: VisionMissionRoute,
  VisionReportsRoute: VisionReportsRoute,
  VisionStrategyRoute: VisionStrategyRoute,
  VisionValuesRoute: VisionValuesRoute,
  VisitVirtualTourRoute: VisitVirtualTourRoute,
  AboutIndexRoute: AboutIndexRoute,
  CareersIndexRoute: CareersIndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  VisionIndexRoute: VisionIndexRoute,
  VisitIndexRoute: VisitIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
