/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitUsRouteImport } from './routes/visit-us'
import { Route as StudentSupportRouteImport } from './routes/student-support'
import { Route as StudentExperienceRouteImport } from './routes/student-experience'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LegacyRouteImport } from './routes/legacy'
import { Route as KuAffiliationRouteImport } from './routes/ku-affiliation'
import { Route as IndustryExposureRouteImport } from './routes/industry-exposure'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CampusLifeRouteImport } from './routes/campus-life'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'

const VisitUsRoute = VisitUsRouteImport.update({
  id: '/visit-us',
  path: '/visit-us',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSupportRoute = StudentSupportRouteImport.update({
  id: '/student-support',
  path: '/student-support',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentExperienceRoute = StudentExperienceRouteImport.update({
  id: '/student-experience',
  path: '/student-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyRoute = LegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const KuAffiliationRoute = KuAffiliationRouteImport.update({
  id: '/ku-affiliation',
  path: '/ku-affiliation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryExposureRoute = IndustryExposureRouteImport.update({
  id: '/industry-exposure',
  path: '/industry-exposure',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusLifeRoute = CampusLifeRouteImport.update({
  id: '/campus-life',
  path: '/campus-life',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-life': typeof CampusLifeRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/governance': typeof GovernanceRoute
  '/industry-exposure': typeof IndustryExposureRoute
  '/ku-affiliation': typeof KuAffiliationRoute
  '/legacy': typeof LegacyRoute
  '/maintenance': typeof MaintenanceRoute
  '/programs': typeof ProgramsRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/scholarships': typeof ScholarshipsRoute
  '/student-experience': typeof StudentExperienceRoute
  '/student-support': typeof StudentSupportRoute
  '/visit-us': typeof VisitUsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-life': typeof CampusLifeRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/governance': typeof GovernanceRoute
  '/industry-exposure': typeof IndustryExposureRoute
  '/ku-affiliation': typeof KuAffiliationRoute
  '/legacy': typeof LegacyRoute
  '/maintenance': typeof MaintenanceRoute
  '/programs': typeof ProgramsRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/scholarships': typeof ScholarshipsRoute
  '/student-experience': typeof StudentExperienceRoute
  '/student-support': typeof StudentSupportRoute
  '/visit-us': typeof VisitUsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-life': typeof CampusLifeRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/governance': typeof GovernanceRoute
  '/industry-exposure': typeof IndustryExposureRoute
  '/ku-affiliation': typeof KuAffiliationRoute
  '/legacy': typeof LegacyRoute
  '/maintenance': typeof MaintenanceRoute
  '/programs': typeof ProgramsRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/scholarships': typeof ScholarshipsRoute
  '/student-experience': typeof StudentExperienceRoute
  '/student-support': typeof StudentSupportRoute
  '/visit-us': typeof VisitUsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/admissions'
    | '/campus-life'
    | '/careers'
    | '/contact'
    | '/governance'
    | '/industry-exposure'
    | '/ku-affiliation'
    | '/legacy'
    | '/maintenance'
    | '/programs'
    | '/publications'
    | '/research'
    | '/scholarships'
    | '/student-experience'
    | '/student-support'
    | '/visit-us'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/admissions'
    | '/campus-life'
    | '/careers'
    | '/contact'
    | '/governance'
    | '/industry-exposure'
    | '/ku-affiliation'
    | '/legacy'
    | '/maintenance'
    | '/programs'
    | '/publications'
    | '/research'
    | '/scholarships'
    | '/student-experience'
    | '/student-support'
    | '/visit-us'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/admissions'
    | '/campus-life'
    | '/careers'
    | '/contact'
    | '/governance'
    | '/industry-exposure'
    | '/ku-affiliation'
    | '/legacy'
    | '/maintenance'
    | '/programs'
    | '/publications'
    | '/research'
    | '/scholarships'
    | '/student-experience'
    | '/student-support'
    | '/visit-us'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  CampusLifeRoute: typeof CampusLifeRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  GovernanceRoute: typeof GovernanceRoute
  IndustryExposureRoute: typeof IndustryExposureRoute
  KuAffiliationRoute: typeof KuAffiliationRoute
  LegacyRoute: typeof LegacyRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ProgramsRoute: typeof ProgramsRoute
  PublicationsRoute: typeof PublicationsRoute
  ResearchRoute: typeof ResearchRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  StudentExperienceRoute: typeof StudentExperienceRoute
  StudentSupportRoute: typeof StudentSupportRoute
  VisitUsRoute: typeof VisitUsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visit-us': {
      id: '/visit-us'
      path: '/visit-us'
      fullPath: '/visit-us'
      preLoaderRoute: typeof VisitUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-support': {
      id: '/student-support'
      path: '/student-support'
      fullPath: '/student-support'
      preLoaderRoute: typeof StudentSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-experience': {
      id: '/student-experience'
      path: '/student-experience'
      fullPath: '/student-experience'
      preLoaderRoute: typeof StudentExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy': {
      id: '/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof LegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ku-affiliation': {
      id: '/ku-affiliation'
      path: '/ku-affiliation'
      fullPath: '/ku-affiliation'
      preLoaderRoute: typeof KuAffiliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-exposure': {
      id: '/industry-exposure'
      path: '/industry-exposure'
      fullPath: '/industry-exposure'
      preLoaderRoute: typeof IndustryExposureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-life': {
      id: '/campus-life'
      path: '/campus-life'
      fullPath: '/campus-life'
      preLoaderRoute: typeof CampusLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  CampusLifeRoute: CampusLifeRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  GovernanceRoute: GovernanceRoute,
  IndustryExposureRoute: IndustryExposureRoute,
  KuAffiliationRoute: KuAffiliationRoute,
  LegacyRoute: LegacyRoute,
  MaintenanceRoute: MaintenanceRoute,
  ProgramsRoute: ProgramsRoute,
  PublicationsRoute: PublicationsRoute,
  ResearchRoute: ResearchRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  StudentExperienceRoute: StudentExperienceRoute,
  StudentSupportRoute: StudentSupportRoute,
  VisitUsRoute: VisitUsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
