/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CampusLifeRouteImport } from './routes/campus-life'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'

const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusLifeRoute = CampusLifeRouteImport.update({
  id: '/campus-life',
  path: '/campus-life',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-life': typeof CampusLifeRoute
  '/contact': typeof ContactRoute
  '/maintenance': typeof MaintenanceRoute
  '/programs': typeof ProgramsRoute
  '/research': typeof ResearchRoute
  '/scholarships': typeof ScholarshipsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-life': typeof CampusLifeRoute
  '/contact': typeof ContactRoute
  '/maintenance': typeof MaintenanceRoute
  '/programs': typeof ProgramsRoute
  '/research': typeof ResearchRoute
  '/scholarships': typeof ScholarshipsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-life': typeof CampusLifeRoute
  '/contact': typeof ContactRoute
  '/maintenance': typeof MaintenanceRoute
  '/programs': typeof ProgramsRoute
  '/research': typeof ResearchRoute
  '/scholarships': typeof ScholarshipsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/admissions'
    | '/campus-life'
    | '/contact'
    | '/maintenance'
    | '/programs'
    | '/research'
    | '/scholarships'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/admissions'
    | '/campus-life'
    | '/contact'
    | '/maintenance'
    | '/programs'
    | '/research'
    | '/scholarships'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/admissions'
    | '/campus-life'
    | '/contact'
    | '/maintenance'
    | '/programs'
    | '/research'
    | '/scholarships'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  CampusLifeRoute: typeof CampusLifeRoute
  ContactRoute: typeof ContactRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ProgramsRoute: typeof ProgramsRoute
  ResearchRoute: typeof ResearchRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-life': {
      id: '/campus-life'
      path: '/campus-life'
      fullPath: '/campus-life'
      preLoaderRoute: typeof CampusLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  CampusLifeRoute: CampusLifeRoute,
  ContactRoute: ContactRoute,
  MaintenanceRoute: MaintenanceRoute,
  ProgramsRoute: ProgramsRoute,
  ResearchRoute: ResearchRoute,
  ScholarshipsRoute: ScholarshipsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
